Feature/users
camila-vecindario/challenge_front pull request #1
Opened 2021-03-11 17:37 UTC by camila-vecindario

Create mock for:
* Login
* Signup
* Projects Screen
* Project Lead form 

Configuration:
* Redux toolkit for state management
* use-react-form for forms, whit input component generalization.
* Yup for form validation
* Bulma for modal behaviour 

The app has mock data. You can change the role in the userSlice initial state, to see little UI variations.

2021-03-11 18:59 UTC, jesus-vecindario requested changes

2021-03-11 18:59 UTC, jesus-vecindario commented on src/App.css
> +
jaja que es esto?

2021-03-11 18:59 UTC, jesus-vecindario commented on src/components/inputs/Input.css
> +C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/sass-3.5.1/lib/sass/tree/visitors/perform.rb:183:in `with_environment'
...

2021-03-11 18:59 UTC, jesus-vecindario commented on src/components/layout/Layout.css
> +C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/sass-3.5.1/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
...

2021-03-11 18:59 UTC, jesus-vecindario commented on src/components/layout/Layout.js
> +  const handleSignUp = () => history.push('/sign-up');
las rutas podrias agregarlas a un archivo de constants, por si luego cambian no toque cambiar ruta por ruta

2021-03-11 18:59 UTC, jesus-vecindario commented on src/components/projects/leadModal/LeadModal.css
> +C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/sass-3.5.1/lib/sass/tree/visitors/base.rb:36:in `visit'
...

2021-03-11 18:59 UTC, jesus-vecindario commented on src/components/projects/projectCard/ProjectCard.css
> +C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/sass-3.5.1/lib/sass/tree/visitors/perform.rb:190:in `visit_root'
...

2021-03-11 18:59 UTC, jesus-vecindario commented on src/components/projects/projectsHeader/ProjectsHeader.css
> +C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/sass-3.5.1/lib/sass/tree/visitors/base.rb:36:in `block in visit'
...

2021-03-15 12:35 UTC, camila-vecindario commented on src/App.css
> +
Removed file

2021-03-15 12:36 UTC, camila-vecindario commented on src/components/inputs/Input.css
> +C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/sass-3.5.1/lib/sass/tree/visitors/perform.rb:183:in `with_environment'
Removed file

2021-03-15 12:36 UTC, camila-vecindario commented on src/components/layout/Layout.css
> +C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/sass-3.5.1/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
Removed files

2021-03-15 12:37 UTC, camila-vecindario commented on src/components/projects/leadModal/LeadModal.css
> +C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/sass-3.5.1/lib/sass/tree/visitors/base.rb:36:in `visit'
Removed files

2021-03-15 12:37 UTC, camila-vecindario commented on src/components/projects/projectsHeader/ProjectsHeader.css
> +C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/sass-3.5.1/lib/sass/tree/visitors/base.rb:36:in `block in visit'
Removed files

2021-03-15 12:38 UTC, camila-vecindario commented on src/components/layout/Layout.js
> +  const handleSignUp = () => history.push('/sign-up');
Las rutas ya se manejan en un archivo: src/constants/routes.js

2021-03-15 21:40 UTC, jesus-vecindario commented on .gitignore
> +*.css.map
De momento por agilidad en este proyecto como te habia dicho está bien, tienes que buscas la forma de que estos archivos no se generen

2021-03-15 22:10 UTC, jesus-vecindario requested changes

2021-03-15 22:10 UTC, jesus-vecindario commented on path/to/css
> +  content: "Errno::ENOENT: No such file or directory @ rb_sysopen - path/to/sass"; }
Borrar

2021-03-15 22:10 UTC, jesus-vecindario commented on src/App.js
> +  R_NOT_FOUND,
Podrias usar nombres mas dicientes, R_ no dice que es al leer el codigo mas abajo. Podria ser algo como HOME_ROUTE, LOGIN_ROUTE ...

2021-03-15 22:10 UTC, jesus-vecindario commented on src/components/privateRoute/PrivateRoute.js
> +  const token = localStorage.getItem('token');
Podrias crear una funcion para obtener y/o asignar atributos en el local storage. A veces puede fallar la app si no es posible acceder al localstorage

2021-03-15 22:10 UTC, jesus-vecindario commented on src/components/users/userProfile/UserProfile.js
> +  };
Se puede agregar useCallback y evitar declarar la función cada vez que se rerenderiza

2021-03-15 22:10 UTC, jesus-vecindario commented on src/components/layout/Layout.js
>    let history = useHistory();
const

2021-03-15 22:10 UTC, jesus-vecindario commented on src/components/users/userProfile/UserProfile.js
> +  let history = useHistory();
const

2021-03-15 22:10 UTC, jesus-vecindario commented on src/pages/project/projectDetail/ProjectDetail.js
> +    const project = projects.find(pro => pro.id.toString() === projectId);
evita declarar variables como `pro`

2021-03-15 22:10 UTC, jesus-vecindario commented on src/pages/project/projectDetail/ProjectDetail.js
> +const MenuItem = ({ to, icon, title }) => {
Siendo un componente visual seria bueno usar memo para evitar rerenders innecesarios

2021-03-15 22:10 UTC, jesus-vecindario commented on src/pages/project/projectForm/ProjectForm.js
> +  name: Yup.string().required('El nombre es requerido'),
Los mensajes de error tambien podrian ir en un archivo de constantes, he visto algunos repetidos

2021-03-15 22:10 UTC, jesus-vecindario commented on src/pages/project/projectForm/ProjectForm.js
> +  const types = Object.keys(projectTypes);
podrias usar useMemo, para evitar declarar la variable en cada rerender

2021-03-15 22:10 UTC, jesus-vecindario commented on src/redux/slices/userSlice.js
>    initialState: {
Trata de inicializar el state fuera del slice para poder exportarlo en caso de quererlo usar por ejm en los tests

2021-03-15 22:10 UTC, jesus-vecindario commented on style.css
> +  content: "Errno::ENOENT: No such file or directory @ rb_sysopen - style.scss"; }
Borrar

2021-03-16 02:15 UTC, camila-vecindario commented on src/App.js
> +  R_NOT_FOUND,
Nombres actualizados

2021-03-16 02:18 UTC, camila-vecindario commented on path/to/css
> +  content: "Errno::ENOENT: No such file or directory @ rb_sysopen - path/to/sass"; }
Eliminado

2021-03-16 02:19 UTC, camila-vecindario commented on src/components/layout/Layout.js
>    let history = useHistory();
Actualizado

2021-03-16 02:23 UTC, camila-vecindario commented on src/components/privateRoute/PrivateRoute.js
> +  const token = localStorage.getItem('token');
Métodos implementados en helpers/utils.js: 
- saveToLocalStorage
- getFromLocalStorage

2021-03-16 02:25 UTC, camila-vecindario commented on src/components/users/userProfile/UserProfile.js
> +  let history = useHistory();
Actualizado

2021-03-16 02:27 UTC, camila-vecindario commented on src/pages/project/projectDetail/ProjectDetail.js
> +    const project = projects.find(pro => pro.id.toString() === projectId);
Variable cambiada a project

2021-03-16 02:52 UTC, camila-vecindario commented on src/pages/project/projectForm/ProjectForm.js
> +  name: Yup.string().required('El nombre es requerido'),
Ahora se manejan los errores de validación de schemas en constants/errorsMessages.js

2021-03-16 02:56 UTC, camila-vecindario commented on src/pages/project/projectForm/ProjectForm.js
> +  const types = Object.keys(projectTypes);
![image](https://user-images.githubusercontent.com/79669772/111249105-28923500-85d9-11eb-8a0b-d6343668f10c.png)
Para este caso, al usar un valor externo (projectTypes), no causa rerenders

2021-03-16 02:58 UTC, camila-vecindario commented on src/redux/slices/userSlice.js
>    initialState: {
Podrías ampliar un poco esto, por favor

2021-03-16 02:59 UTC, camila-vecindario commented on style.css
> +  content: "Errno::ENOENT: No such file or directory @ rb_sysopen - style.scss"; }
Eliminado

2021-03-16 03:00 UTC, camila-vecindario commented on src/components/users/userProfile/UserProfile.js
> +  };
¿Se haría con todas las funciones?

2021-03-16 03:10 UTC, camila-vecindario commented on src/pages/project/projectDetail/ProjectDetail.js
> +const MenuItem = ({ to, icon, title }) => {
Aprendido e implementado :D

2021-03-17 13:11 UTC, jesus-vecindario commented on src/components/users/userProfile/UserProfile.js
> +  };
No, no es necesario en todas las funciones, era mas como una recomendación, pero no siempre es util, en componentes mas grandes y que se rerenderice mas es mas util, o tambien cuando le pasas la función a un componente hijo y solo necesitas q se rerenderice cuando cambia cierta prop. En este caso especifico depronto tendria un mejor comportamiento si lo usas en handleOpenOptions en las demas no seria necesario.

2021-03-17 13:19 UTC, jesus-vecindario commented on src/pages/project/projectForm/ProjectForm.js
> +  const types = Object.keys(projectTypes);
mmm interesante 🤯 jaja, aunque en este caso no creo que sea una operación costosa, lo decia era porque en cada rerender causado por otra variable el componente volveria a calcular la variable types. No sé si esté en lo correcto. Tambien podrias dejar ese types dentro de projectsConstants por si en alguna otra parte se utiliza y en algun momento hay q filtrar o algo por el estilo

2021-03-17 13:23 UTC, jesus-vecindario commented on src/redux/slices/userSlice.js
>    initialState: {
Obvio. Para testing se usa esta libreria para hacer un mock del store de redux [redux-mock-store](https://github.com/reduxjs/redux-mock-store). Entonces para evitar volver a llenar el estado inicial cuando se inicializa se importan los estados iniciales, y eso tambien evita que por ejm agregues una nueva variable y el test falle porque estés tratando de acceder a un atributo de esa variable. Aunque aun esto no lo usamos mucho que digamos 😅

2021-03-17 13:27 UTC, jesus-vecindario commented on src/components/table/Table.js
> +export default Table;
Está bien la implementación. Solo mira [react-table](https://github.com/tannerlinsley/react-table). La hemos venido usando en los ultimos proyectos, creo que en simula y vecindario aun no está, pero como para que la tengas en el radar

2021-03-17 13:30 UTC, jesus-vecindario commented on src/helpers/utils.js
> +  localStorage.setItem(key, value);
Podrias agregar una validación como typeof(Storage) !== 'undefined'

2021-03-17 13:34 UTC, jesus-vecindario approved these changes

2021-03-19 02:26 UTC, merged